### PR TITLE
creates `UserAccessToken` component

### PR DESCRIPTION
**Pull request by katydecorah**
@langsmith this PR adds a `UserAccessToken` component which will make it much easier to get the user's access token, or if they are sign out display: `YOUR_MAPBOX_ACCESS_TOKEN`. I'm hoping this will work with your implementation - would you like to test it out to confirm?

Here's how to use the component:

To use it, you'll first want to import the component (usually added to prependJs in the frontmatter):

```js
import UserAccessToken from '../../../components/user-access-token';
```

Place `{{ <UserAccessToken /> }}` in the code where you want the access token to print out.

fixes https://github.com/mapbox/android-docs/issues/662

### CODE REVIEW

**Comment by langsmith** [comment]
Incredible, @katydecorah 

giphy-2

**Comment by langsmith** [comment]
Tried it out, but the Java/Kotlin code snippets seem to be an issue. Tokens are often referenced in actual code snippets, but the component doesn't affect the code snippets.

screen shot 2019-01-08 at 12 03 56 pm
screen shot 2019-01-08 at 12 03 53 pm


There _are_ some pages which reference a token or reference getting a token. Using the component there could work as a start. 

screen shot 2019-01-08 at 12 09 50 pm

**Comment by katydecorah** [comment]
@langsmith ooh super helpful! I'll take a closer look at the code snippets to see if we can get the tokens to work in there as well

**Comment by katydecorah** [comment]
@langsmith the latest commit replaces the access token placeholder text with the user's token from inside the `ToggleableCodeBlock` component. I'm hoping this will work 🤞, please let me know if there are other instances I should think about.

**Comment by langsmith** [comment]
Pushed two commits to update all token references to the standard `MAPBOX_ACCESS_TOKEN`. Token shows up!

screen shot 2019-01-11 at 4 20 22 pm

**Comment by langsmith** [comment]
Don't know if you want someone to review your code @katydecorah , but I gave you ✅ on my front

**Pull request merged**
