### PR TITLE
Updating maps examples with demo app list

### PR DESCRIPTION
**Pull request by langsmith**
This pr brings https://www.mapbox.com/android-docs/maps/examples/ much more up-to-date with the list of examples found in https://github.com/mapbox/mapbox-android-demo

### CODE REVIEW

**Comment by langsmith** [comment]
For https://github.com/mapbox/android-docs/blob/mb-pages/CONTRIBUTING.md#update-examples, where am I running `git submodule update --remote examples/maps`? In this repo? In https://github.com/mapbox/mapbox-android-demo ? Does this create the files found in `src/example-code/ `? Or do I need to manually make those files for the activities/examples which I'm adding in this pr?

When I run `bin/appropriate-images.js --all` on this pr, I get 
screen shot 2018-11-05 at 3 27 58 pm

I get the same error after I run `npm install`

**Comment by langsmith** [comment]
WIP @colleenmcginnis , so no need for actual review at the moment

**Comment by langsmith** [comment]
`npm start` issue has been solved

**Comment by colleenmcginnis** [comment]
Ooook @langsmith I think https://github.com/mapbox/android-docs/pull/712/commits/5cebb9e954021cd6ce87eb85e04e37c9990f7c6c resolves most of the errors. It looks like we are still missing one video `example-recyclerview-interaction.mp4`. Is that something you can add? I can do a final review after that video is added!

**Comment by langsmith** [comment]
@colleenmcginnis , I just added the `example-recyclerview-interaction.mp4` video

**Comment by langsmith** [comment]
@colleenmcginnis , the individual example pages with videos don't load for me when I click on a http://localhost:8080/android-docs/maps/examples/ card . Does it work for you?

**Comment by langsmith** [comment]
Still not working for me @colleenmcginnis .

I did `rm -rf node_modules/`, then `npm install`, and then `npm start`. 

screen shot 2018-11-15 at 12 37 43 pm



I get a blank white browser screen when I click on the picture-in-picture card

screen shot 2018-11-15 at 12 36 13 pm

**Pull request merged**
