### PR TITLE
Updated examples submodule to refresh examples

### PR DESCRIPTION
**Pull request by langsmith**
This pr updates the submodule to update various examples to match what's in the demo app.

I followed instructions at:

- https://github.com/mapbox/android-docs/blob/publisher-production/CONTRIBUTING.md#update-examples

- https://github.com/mapbox/android-docs/blob/publisher-production/CONTRIBUTING.md#add-a-new-example

This pr also adds a new video for https://docs.mapbox.com/android/maps/examples/query-a-map-feature/ because the example was refactored in the demo app: https://github.com/mapbox/mapbox-android-demo/pull/1148

### CODE REVIEW

**Comment by langsmith** [comment]
@colleenmcginnis , my Terminal as I did the update

Screen Shot 2019-07-30 at 12 24 43 PM

**Comment by langsmith** [comment]
Just bumping code

**Comment by langsmith** [comment]
We good here @colleenmcginnis ? Something more you want to look into?

**Comment by langsmith** [comment]
@colleenmcginnis , I need you to clear the Travis cache when you get a chance. I can't do it myself. Thanks.

**Comment by danswick** [comment]
I noticed that our node versions were a bit out of sync between our `.travis.yml` and our `.nvmrc` file. The failures we were attributing to cache issues look more likely to have originated from Travis ignoring our `package-lock` file. Unfortunately, it looks like [Node v9 never shipped](https://nodejs.org/de/download/releases/) with a version of `npm` that supported `npm ci` (npm version >=5.7.0). 

I made a change to our travis and nvm configs that should address this issue by: 

1. bumping to Node v8.16.0 in our `.nvmrc` file. Node 8 is still LTS and recent versions ship with an up-to-date version of npm. 
2. removing the node version from our `.travis.yml` file, forcing Travis' `nvm install` command to fall back to the version we've specified in our `.nvmrc` file. 

This should keep Travis' versions and such in sync with what we're doing locally 👍 

cc @katydecorah

**Pull request merged**
