### PR TITLE
Updating examples on maps sdk docs examples page

### PR DESCRIPTION
**Pull request by langsmith**
This pr updates https://docs.mapbox.com/android/maps/examples/ to account for the several new examples added to https://github.com/mapbox/mapbox-android-demo in the last 1-2 weeks. Markdown files, code files, and videos are added in this pr.

### CODE REVIEW

**Comment by langsmith** [comment]
Gahh, need to adjust the markdown files' topic sections

**Comment by langsmith** [comment]
markdown files have been adjusted

**Comment by langsmith** [comment]
When I locally test, I keep getting similar errors for all of the examples I've added in this pr 😢 

Screen Shot 2019-04-10 at 11 44 59 AM
Screen Shot 2019-04-10 at 11 44 44 AM

**Comment by colleenmcginnis** [comment]
Weird. It's looking for `.js` files, but those should be `.java` files. I can't dig in right now, but can hopefully revisit before the end of the week.

**Comment by colleenmcginnis** [comment]
Ok @langsmith I fixed the script (https://github.com/mapbox/android-docs/pull/916/commits/b7fabb9a99adb5397184bf03406afcfe316f90d0 🤦‍♀️) and updated the examples in this PR that were messed up because of the error in the script (https://github.com/mapbox/android-docs/pull/916/commits/33fc7bfad4c173a4981f2eebaf45b63fbb9362c4).

It looks like you have one tiny error causing the test to fail:
```
src/pages/plugins/examples/symbol-listener.md
  1:1-11:4  error  description must end with a period  mapbox-frontmatter  remark-lint
```

**Comment by langsmith** [comment]
Thank you @colleenmcginnis 💪

**Comment by langsmith** [comment]
@colleenmcginnis , https://travis-ci.com/mapbox/android-docs/builds/108567978 failed because the files were missing the new `contentType` and `language`. I manually added them in https://github.com/mapbox/android-docs/pull/916/commits/4651ddb05b59fbce18e3824639ed9b76a584604d

 I don't remember if your script does, but perhaps you can check to see if it's set up to add those two new frontmatter items to the standard markdown file generation....

**Comment by langsmith** [comment]
Great, thanks @colleenmcginnis . Just ran `npm start` and the new videos/pages are looking 💯 . Will merge when the tests pass.

**Comment by langsmith** [comment]
cc @osana as fyi on some downstream ⚙️ that move when examples get added to https://github.com/mapbox/mapbox-android-demo

**Pull request merged**
