### PR TITLE
Add missing demo app examples to maps/plugins docs examples sections

### PR DESCRIPTION
**Pull request by langsmith**
The long and arduous process of resolving https://github.com/mapbox/android-docs/issues/831 is in this pr's work.

Adds [demo app](https://github.com/mapbox/mapbox-android-demo) examples to https://docs.mapbox.com/android/maps/examples/, https://docs.mapbox.com/android/plugins/examples/, etc.

- [x] KotlinSimpleMapViewActivity.kt
- [x] BathymetryActivity.java
- [x] CircleLayerClusteringActivity.java
- [x] KotlinStyleCirclesCategoricallyActivity.kt
- [x] LineGradientActivity.java
- [x] SatelliteLandSelectActivity.java
- [x] GeocodingActivity.java (in https://www.mapbox.com/android-docs/java/examples/)
- [x] IsochroneActivity.java (in https://www.mapbox.com/android-docs/java/examples/)
- [x] TilequeryActivity.java (in https://www.mapbox.com/android-docs/java/examples/)
- [ ] AnimatedImageGifActivity.java
- [x] CalendarIntegrationActivity.java
- [x] DashedLineDirectionsPickerActivity.java (in https://www.mapbox.com/android-docs/java/examples/)
- [x] LocationPickerActivity.java
- [ ] MagicWindowKotlinActivity.kt
- [x] MapFogBackgroundActivity.java
- [x] MarkerFollowingRouteActivity.java
- [x] SnakingDirectionsRouteActivity.java
- [x] SpaceStationLocationActivity.java
- [x] KotlinLocationComponentActivity.kt
- [x] LocationComponentOptionsActivity.java
- [x] MarkerViewPluginActivity.java (https://www.mapbox.com/android-docs/plugins/examples/)
- [x] ClickToAddImageActivity.java

### CODE REVIEW

**Comment by colleenmcginnis** [comment]
👋 @langsmith I have a rough draft of a script that will do the following (the output is essentially everything included in this commit https://github.com/mapbox/android-docs/pull/835/commits/4f4b948be1c7ad2e42781d858c29c5f3501c4b31):

- Checks for unused Activities in the `examples/maps/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/` folder.
- For each unused Activity it creates the set of files needed to display an example web page including:
  - a js file in the `src/example-code/` folder
  - an md file in the appropriate `src/pages/{product}/examples/` folder
  - a placeholder thumbnail image in the `conf/image-config.js` file

There are a few things that still need to be done manually as of right now (and I'm not sure we'll ever really be able to automate): 
- Write a `description` in each md file (tests will fail without descriptions)
- Add a `topic` in each md file
- Add a full-size image or video and a thumbnail to replace the placeholder

Here's what the output in the Java SDK docs looks like right now (no thumbnail, no description, no topic title for the section): 

Screen Shot 2019-03-22 at 1 30 48 PM

Finally, there are a few things I'm still working on:

- [ ] Refactor updating image config
- [ ] See if we can grab the `description` from [this part](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/basics/MapboxMapOptionActivity.java#L18) of the demo Activities
- [ ] Update code toggling and syntax highlighting for examples using Kotlin
- [ ] Add support for navigation examples

**Comment by colleenmcginnis** [comment]
Ooook @langsmith. I made a few more updates to the script: 

- Pulls titles from the demo app’s `titles_strings.xml` file
- Pulls descriptions from the demo app’s `descriptions_strings.xml` file
- Pulls thumbnail images from the demo app’s `urls_strings.xml` file
- Assigns a `topic` where appropriate according to [this object](https://github.com/mapbox/android-docs/pull/835/files#diff-c926c4c2ea781cffe784102a9606bb26R94)
- Adds the option to run on navigation examples (https://github.com/mapbox/android-docs/pull/835/commits/3c340bb87c0f2bd50a9712ea92aaff4c655e3e28)
- Adds the option to run on one activity (https://github.com/mapbox/android-docs/pull/835/commits/28e72d443fdce3fbbb8ff4d4ff9babb99a4f525c)

Then I made some manual changes:

- Resolved failing tests (mostly adding `.` to the end of descriptions) (https://github.com/mapbox/android-docs/pull/835/commits/5392584e8c9c6300f10f2a4bfe0a73a358f43d46)
- Adds Kotlin code to relevant examples (https://github.com/mapbox/android-docs/pull/835/commits/c197ffc0c43e57a9d9444474b46d0f82685b4eb6)
- Adjusts the max height of code snippets (https://github.com/mapbox/android-docs/pull/835/commits/fbcca8a4cee381a02eae7fcb86d18bbe44c192a1)

There are a few things that still need to be done: 

- [ ] @langsmith add images or videos to new example pages
- [ ] @langston add `topic` to the front matter of new example pages
- [ ] @colleenmcginnis update README
- [ ] @danesfeder to confirm that additions to `navigation/examples/` page are appropriate
- [ ] @colleenmcginnis remove unused images

**Comment by langsmith** [comment]
Ok, so these are the new example pages added in this pr. 


Screen Shot 2019-03-25 at 3 28 35 PM
Screen Shot 2019-03-25 at 3 28 31 PM
Screen Shot 2019-03-25 at 3 28 25 PM
Screen Shot 2019-03-25 at 3 28 21 PM

**Comment by langsmith** [comment]
Videos are always preferable to images on each example page. If possible, I'd love for the script to add the following two lines to the `prependJs:` section:

```
  - "import { VideoWithDeviceFrame } from '../../../components/video-with-device-frame'"
  - "import videoEXAMPLENAME from '../../../video/example-EXAMPLENAME.mp4'"
```

and then add this in the `.md` file

```
{{
  <VideoWithDeviceFrame 
    videoFile={videoEXAMPLENAME}
    rotation="vertical"
    device="pixel-2"
  />
}}
```

EXAMPLENAME is auto-generated via pulling info from the demo app example....

**Comment by langsmith** [comment]
Are the additions in my comment above, possible? If so, I'll hold off on working on this pr until the new `.md` files get the additions so that I don't have to manually add them to each new `.md` file in this pr.

**Comment by colleenmcginnis** [comment]
@langsmith yes definitely possible. I'm heads down on something else now, but I can make those updates tomorrow morning. Feel free to work on recording/adding videos with file names that conform to the naming pattern you described above.

**Comment by colleenmcginnis** [comment]
@langsmith I updated the script and ran it to update the md files to use `VideoWithDeviceFrame` by default (https://github.com/mapbox/android-docs/pull/835/commits/155d2412b0825a0791a57eca623b8491e9c85236). The example file names should be in the `src/videos/` folder and the name should follow this pattern: `example-{activity-name-with-dashes}.mp4`. JFYI the example pages will not load until you add the videos to the `src/videos/` folder -- there will be an error that it can't find the mp4 file you're trying to import. Let me know if you have any questions or other suggestions!

**Comment by langsmith** [comment]
>I updated the script and ran it to update the md files to use VideoWithDeviceFrame by default


ezgif com-optimize


Thank you! I'll keep chipping away at adding the videos

**Comment by langsmith** [comment]
Ok @colleenmcginnis . My latest commits have brought things up to speed.

Videos are looking good. Checklist in OP has been updated.  

- `AnimatedImageGifActivity.java` isn't working in the demo app. Maybe we remove it from the list of examples that show up in `/android/maps/examples/` until I get it working. 
- Can you work your (scripting) magic to pull in `MagicWindowKotlinActivity.kt`? It's Kotlin-only.

The categories are a bit helter skelter, but are fine for now IMO. Not blockers for this pr. 
Screen Shot 2019-03-27 at 2 46 38 PM

**Comment by colleenmcginnis** [comment]
@langsmith my recommendation would be to move the rest of the work to follow-up PRs including: 

- Adding the `AnimatedImageGifActivity.java` example since the current demo is broken. 
- Adding `MagicWindowKotlinActivity.kt`. Since it's Kotlin-only, we should think about how we want to communicate that it is a Kotlin example. Currently if a code block does not have a toggle, it's always Java. If we're going to start breaking that pattern we should think about how we want to communicate that. I can take the lead on that in a follow-up PR.
- Adding new Navigation SDK examples. I removed those from this PR, and I'll open a fresh PR for @danesfeder to review -- that should be a little easier to review. 

If those final action items sound ok to you, let's do one final review tomorrow morning and get these examples out to users! 🙂

**Comment by langsmith** [comment]
All of that sounds good @colleenmcginnis .

**Pull request merged**
