### PR TITLE
Moved NavView chart to markdown

### LINKED ISSUE #553: Convert NavigationView Color Map to markdown table
#551 landed adding a `.png` color map for the Navigation SDK `NavigationView`.  We convert this to a   markdown table to make it more accessible / easier to maintain as @colleenmcginnis pointed out in https://github.com/mapbox/android-docs/pull/551#issuecomment-404224883

### PR DESCRIPTION
**Pull request by langsmith**
Closes #553 

Moves the navigationView chart from the image to a markdown table based on @colleenmcginnis 's comment: https://github.com/mapbox/android-docs/pull/551#issuecomment-404224883

screencapture-localhost-8080-android-docs-navigation-overview-navigation-ui-2018-07-11-11_20_20

### CODE REVIEW

**Comment by danesfeder** [comment]
@langsmith the chart looks 💯 thanks for running with that.  Should we reduce the width of the image now that it takes the width of the content area?  It looks a little big to me in the screenshot.

**Comment by langsmith** [comment]
Yea I tried decreasing the size of the image but  🦇🐟 doesn't seem to like the changes I make. Maybe it automatically makes the image fill the width of the content container. Any insight @colleenmcginnis ? 

I kinda' like the current size of the phone image because various letters can easily be viewed. If the image were a lot smaller, it might be harder to tell where arrows are pointing and what `NavigationView` resource is what. :cent: :cent:

**Comment by colleenmcginnis** [comment]
@langsmith see the changes I made to adjust the size of the image in https://github.com/mapbox/android-docs/pull/554/commits/c8b6de320e0d7873ef65f4e64af2acc5ef6b90b6.

@danesfeder do you still have the original file for this image? Right now the image size is only 295px wide, so it looks quite pixelated on high res screens.

**Comment by langsmith** [comment]
@colleenmcginnis , I'll send you the original file for the image

**Comment by langsmith** [comment]
💥 Great work team ✔️

**Pull request merged**
