### PR TITLE
[404 patrol] fix broken links

### PR DESCRIPTION
**Pull request by katydecorah**
While making the 404 patrol rounds this morning, I found three broken links. I was able to resolve one, but will need some assistance on the other two that appear in the following dropdown on: https://docs.mapbox.com/android/plugins/overview/china/

image

* https://docs.mapbox.com/android/api/plugins/building/0.5.0/index.html
* https://docs.mapbox.com/android/api/plugins/china/2.0.0/china-release/index.html

@langsmith would you happen to know about the links above? I'm not sure if it's a matter of the docs not getting generated or a malformed url.

### CODE REVIEW

**Comment by langsmith** [comment]
> https://docs.mapbox.com/android/api/plugins/building/0.5.0/index.html

I never made and uploaded the api reference docs for that release.

screen shot 2019-02-26 at 9 21 31 am


> https://docs.mapbox.com/android/api/plugins/china/2.0.0/china-release/index.html

Weird because the `/android-docs` repo has the `2.0.0` docs 🤔 

screen shot 2019-02-26 at 9 23 24 am

**Comment by langsmith** [comment]
> I never made and uploaded the api reference docs for that release.

Which I will do

**Comment by katydecorah** [comment]
Thanks for help 🕵️'ing! The broken link in this PR got fixed in https://github.com/mapbox/android-docs/pull/866 so I'll close here

**Comment by langsmith** [comment]
>Weird because the `/android-docs` repo has the `2.0.0` docs 🤔

https://docs.mapbox.com/android/api/plugins/china/2.0.0/china-release/index.html still doesn't work 🤔  Something I need to do on my end, @katydecorah ?

**Comment by katydecorah** [comment]
@langsmith 🤦‍♂️ I totally over looked that one. I'll get a PR up! Thanks for the bump

**Pull request closed without merging**
