### PR TITLE
Add NavigationView Color Map

### LINKED ISSUE #519: Add NavigationView Theme diagram to define color organization
We offer the ability to change a lot of the colors / attributes of the `NavigationView` in the Navigation SDK.  We should create a diagram that illustrates where each attribute aligns to the actual view when it's inflated. 

https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#styling-the-navigationview

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #519 

Adds a color diagram mapping the Android Navigation SDK style attributes to where they will show in the actual UI: 

navigation-view-color-diagram

cc @akitchen @aag6z

### CODE REVIEW

**Comment by danesfeder** [comment]
@langsmith I may need your help here confirming the image shows okay - I'm still running into configuration issues trying to host locally it seems unfortunately

**Comment by langsmith** [comment]
Looks amazing. Thanks @danesfeder 

>I'm still running into configuration issues trying to host locally it seems unfortunately

@danesfeder , I've got (probably the same) issues as well.   @colleenmcginnis , thoughts on a solution for us? Can you at least confirm that the image is looking 💯 so that we can merge this pr for now?

**Comment by langsmith** [comment]
`npm install` fixed it for me @colleenmcginnis

**Comment by langsmith** [comment]
Looks good @danesfeder . Fyi, whenever you add images to a page in this repo, you should run `bin/appropriate-images.js --all` to optimize them. If you don't, the page won't load when testing locally.


screen shot 2018-07-10 at 5 34 05 pm


Mobile preview:

screen shot 2018-07-10 at 5 34 53 pm

**Comment by danesfeder** [comment]
Thank you for the help @langsmith @colleenmcginnis! 🚀

**Comment by colleenmcginnis** [comment]
This is great @danesfeder! We should consider building the table in markdown file for this page. Text in images is something to avoid since it makes content less accessible (for screen readers and machine translation).

**Comment by danesfeder** [comment]
@colleenmcginnis great idea - this would make it easier to maintain as well https://github.com/mapbox/android-docs/issues/553

**Comment by langsmith** [comment]
I'll make the markdown table in a new pr

**Comment by akitchen** [comment]
This is fantastic @danesfeder !

We should talk about automating keeping this up to date as the SDK continues to evolve.

**Pull request merged**
