### PR TITLE
Camera doc

### PR DESCRIPTION
**Pull request by cammace**

### CODE REVIEW

**Comment by cammace** [comment]
@mapbox/android do we have any initial feedback for this doc to help @langsmith write it? Right now we are going section by section and just writing down notes of what to talk about in each section, It would be great if everyone could help fill in these sections with ideas and common questions that come through HS/SO.

**Comment by cammace** [comment]
@langsmith this looks great so far, I went ahead and made a few edits and missing information. Only a few sections left to fill out.

**Comment by cammace** [comment]
@langsmith can we go ahead and wrap this doc up by finishing the last few sections?

**Comment by langsmith** [comment]
_Note__ this pr would fix #17

**Comment by aboshab2** [comment]
بتاريخ ٢٠١٧/٠٧‏/٢٧ ٨:٢٤ م، كتب "Langston Smith" <notifications@github.com>:

**Pull request merged**
