### PR TITLE
Map Events Doc

### PR DESCRIPTION
**Pull request by cammace**
Closes https://github.com/mapbox/android-docs/issues/59

This document is intended to walk through the various map events developers can listen to. @tobrun @Guardiola31337 Am I missing any events worth mentioning in this doc? I currently list:

- click and long click
- camera change events (Updated for 5.1 APIs)
- marker and info window events
- map change events

cc: @mapbox/android

### CODE REVIEW

**Comment by tobrun** [comment]
On top of my head: 
- We expose some additional gesture listeners:
  - MapboxMap.OnFlingListener
  - MapboxMap.OnScrollListener

- Developers can listen to location change events
- Developers can listen to location tracking/bearing change events
- Developers can listen to style finished loading event

**Comment by cammace** [comment]
Awesome, I'll add the fling and scroll events. For location, I'm thinking this should go into a different document for LocationSource?

**Comment by cammace** [comment]
Docs first draft has been finished, would be great to get some 👀 on it to make sure everything's correct.

**Comment by cammace** [comment]
Any takers on reviewing this PR or should I just merge 😉

**Comment by Guardiola31337** [comment]
@cammace 
More map events:

- [`OnFpsChangedListener`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L2069-L2081)
- [`SnapshotReadyCallback`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L2395-L2405)

Regarding offline:

- [`ListOfflineRegionsCallback`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java#L48-L66)
- [`CreateOfflineRegionCallback`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java#L68-L86)
- [`OfflineRegionObserver`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java#L56-L99)
- [``]()
- [``]()

**Comment by zugaldia** [comment]
I can't see some of the map events that you list on [`native_map_view`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/native_map_view.hpp#L70-L82) (e.g. `DID_FINISH_RENDERING_FRAME_FULLY_RENDERED`). Are they defined somewhere else?

**Comment by cammace** [comment]
@zugaldia I got the map view events from this [MapChange](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L595) definition.

@Guardiola31337 the offline events are, for the most part, defined inside the offline doc. The Snapshot callback should be placed in a doc more specific to the Snapshot feature we offer. I'll add `OnFpsChanges`, could you give an example what a user would use this for though?

**Comment by Guardiola31337** [comment]
@cammace 
> the offline events are, for the most part, defined inside the offline doc. The Snapshot callback should be placed in a doc more specific to the Snapshot feature we offer.

👍 

> I'll add `OnFpsChanges`, could you give an example what a user would use this for though?

`Sets a callback that's invoked on every frame rendered to the map view.`
It's used internally by `MapView` although the `interface` is public. Right now, I can't think any use case for devs. Anyone?
I wouldn't include it in the docs for the moment.

**Comment by langsmith** [comment]
@cammace , I made some small grammar/spelling tweaks. Looks good to me otherwise.

**Comment by cammace** [comment]
Thanks, @langsmith, this doc's ready to be merged.

**Pull request merged**
