### PR TITLE
Switching to the new Android documentation site

### PR DESCRIPTION
**Pull request by cammace**
This PR officially marks the start of `/android-docs` being the new default Android docs page rather than the outdated `/android-sdk`. This will reduce the duplication work happening between repos currently. Before this can happen, a few things need to be taken care of such as reviewing to ensure all edge cases are covered. 

- [x] Update Readme

**Documentation review:**
- [ ] @langsmith review
- [ ] @zugaldia  review

**Website code review:**
- [x] @davidtheclark review
- [x] @mayagao review

### CODE REVIEW

**Comment by langsmith** [comment]
@cammace , did you want me to just check the one file changed in this PR? I've made a commit on this PR with grammar and sentence structure tweaks. I wasn't sure if my checkbox above includes reviewing other documentation somewhere else...

**Comment by davidtheclark** [comment]
My take on this rewrite with Gatsby is that it means the @mapbox/android is taking on responsibility for the implementation of this site. So if you want to manage the site with Gatsby instead of Jekyll, seems like that's your call. I understand @cammace, at least, has enjoyed working with React on this. 🆒 

At some point in the not-too-distant future, I'm hoping we can port this to a React-powered static-site generator that we'll share across Mapbox projects ([I've started working on this](https://github.com/mapbox/batfish)). Additionally, we'll want to port the implementation of these design patterns (with whatever changes @mapbox/design might settle on) to components that can be re-used on other documentation pages. Because of those points, I think of this Gatsby implementation as a temporary thing. I don't think I have the time to review the details of the codebase, but will instead focus on getting the infrastructure in place to move this out of its temporary phase. If you have any specific questions, though, feel free to ask and I'll try to take a look at those pieces!

**Comment by zugaldia** [comment]
> At some point in the not-too-distant future, I'm hoping we can port this to a React-powered static-site generator that we'll share across Mapbox projects (I've started working on this).

Agreed, @mapbox/android shouldn't be in charge of implementing the site. Instead, we'd like to only curate the content and migrate to this static site generator when it's ready (background on why we're currently using Gatsy is on https://github.com/mapbox/www.mapbox.com/issues/1616#issuecomment-300173277).

@cammace considering all the effort put in this new docs, if you're OK with taking care of the low-level Gatsby implementation meanwhile I'm OK with going ahead with this PR.

**Comment by cammace** [comment]
No issues on my end with maintaining this repo and the low-level Gatsby implementation @zugaldia

**Comment by zugaldia** [comment]
> did you want me to just check the one file changed in this PR? I've made a commit on this PR with grammar and sentence structure tweaks. I wasn't sure if my checkbox above includes reviewing other documentation somewhere else

@langsmith I'd like to use this PR as an opportunity to do a final review to the text that will be published under `/android-docs`. Could I ask you to 1) do that pass to the text, and make any changes you need inside this PR and 2) compare the current content with the soon to be former `android-sdk` site to make sure we're not forgetting to migrate anything?

**Comment by cammace** [comment]
The `/android-sdk` page is now redirected to `/android-docs`.

**Pull request merged**
