### PR TITLE
Updated plugin pages

### PR DESCRIPTION
**Pull request by cammace**
Updated the dependencies in package.json which is why this PR is so big. Changes for the plugins mainly happened [here](https://github.com/mapbox/android-docs/blob/45978599f8f212d18a14526db4873e7e55815e02/src/pages/plugins/overview/index.md).

screenshot-localhost-8080-2018 03 01-15-32-14

Images for the Places and localization plugin still need to be made.

### CODE REVIEW

**Comment by langsmith** [comment]
Looks great @cammace . Check out the tweaks/additions that I committed.

**Comment by colleenmcginnis** [comment]
This is looking good @cammace. I did some light copy-editing on the intro page. I'll continue with the Places guide tomorrow. Here are some other thoughts: 

**The list of plugins on the intro page should match the table of contents.**
We should make sure these two lists are in sync. I don't know which is the source of `truth` right now. It would also be great to get them in the same order. 

image

**Add images using `appropriate-images`**
I added a new section to `CONTRIBUTING.md` about adding images. We should be adding images using this workflow rather than adding them using `` directly in the Markdown files.  

**Icons**
I can work on refining the design of icons later this week. 

**Headings in the Places guide are not consistent.**
We should establish some more intentional hierarchy inside each guide. Do we want to limit `<h2>`s to  installation + UI components? Once we decide we'll need to make sure that this is reflected in the front matter in the Markdown file so headings are passed correctly to the table of contents.

**Comment by colleenmcginnis** [comment]
👋 @cammace I made some copy edits / reorganized some content in the Places plugin guide in https://github.com/mapbox/android-docs/pull/339/commits/fcbc17a761805792a3a6be7d2198c293e2aa55a9. Take a look and let me know if any of my edits made anything `wrong`.

**Comment by cammace** [comment]
This is great feedback @colleenmcginnis, I will go ahead and fix up some of the issues you mentioned.

> I can work on refining the design of icons later this week.

🙇

**Pull request merged**
