### PR TITLE
Several style changes in preparation for 5.1.0 release

### PR DESCRIPTION
**Pull request by cammace**
This PR contains many style-related changes proposed internally, Work so far:

screenshot-0 0 0 0-8000-2017-05-15-10-06-47

cc: @davidtheclark @zugaldia @mayagao @langsmith

### CODE REVIEW

**Comment by cammace** [comment]
The layout is well on it's way to being ready for the 5.1.0 release if the maps SDK. These are the issues I've identified so far that could use some further looking into:

@cammace (with @davidtheclark's help)
- [ ] Popover only showing when clicked on, not when hovered over
- [ ] TOC duplicating document title in some cases
- [ ] Not getting screen size initially causing hidden TOC until windows resized
- [ ] Optimize for mobile usage
- [ ] Button highlighting not filling void 

/Screen Shot 2017-05-17 at 10.19.18 AM 2.png

@langston @cammace
- [ ] At least one tutorial for each SDK needs to be added:
	- [ ] Navigation SDK
	- [ ] Map SDK
	- [ ] Mapbox Services
	- [ ] Plugins

@mayagao 
- [ ] Examples page mock up
- [ ] Second review of site layout

**Comment by langsmith** [comment]
@cammace , I added the Play Store badge and splash image. Clicking on badge goes to the Play Store page. The layout could be improved, but I figured that my commits were at least a start. I originally wanted to have the badge live permanently in the left hand side of the page, but that might not work great for viewing in mobile. Probably best in the end to leave it where I've put it for now.

screen shot 2017-05-25 at 5 15 50 pm

**Comment by langsmith** [comment]
The other thing I'd like to eventually do is make this button more obvious. I couldn't figure out how to do that in React:
350341886868488 5z4bat6kv20nimayr5ta_height640


It's too important to be inconspicious with it's empty fill background and light gray outline. Make it [one of the Mapbox secondary colors](https://www.mapbox.com/styleguide/colors/)?

**Comment by cammace** [comment]
Google Play demo app branding: https://github.com/mapbox/android-docs/issues/63

**Pull request merged**
