### PR TITLE
Hotspot maps are a DDS thing

### PR DESCRIPTION
**Pull request by 1ec5**
Fixed a broken link to a data-driven styling demo.

/cc @langsmith

### CODE REVIEW

**Comment by 1ec5** [comment]
While we’re at it, I think we should rename this demo to call it a “hotspot map” instead of a “heatmap”, both for correctness and in preparation for actual heatmap support in the map SDK: mapbox/mapbox-gl-native#10146.

/cc @danswick

**Comment by langsmith** [comment]
@1ec5 , I've added additional commits to this branch/pr to adjust the name to hotspots.

We should merge [this demo app pr](https://github.com/mapbox/mapbox-android-demo/pull/512) so that the hotspots example card link on this pr doesn't 404

**Comment by langsmith** [comment]
No clue why `stork` is failing 😠

**Comment by 1ec5** [comment]
I guess this is safe to merge now, right?

**Comment by langsmith** [comment]
Fine by me to merge, but the AWS `stork` is new to me and I'm unable to login/explore what's failing. Just ignore for now @1ec5 ?

**Comment by langsmith** [comment]
Ready @1ec5

**Pull request merged**
