### PR TITLE
Updated plugin example list

### PR DESCRIPTION
**Pull request by langsmith**
Resolves https://github.com/mapbox/android-docs/issues/352 by adding more plugins to https://www.mapbox.com/android-docs/plugins/examples/

1-2 unrelated images got automatically swept up in the image optimization process, but it should be fine.

ezgif com-video-to-gif

### CODE REVIEW

**Comment by langsmith** [comment]
ezgif com-video-to-gif

**Comment by cammace** [comment]
It looks like we are optimizing some of the `first steps` guide images which we shouldn't need anymore since this guides hosted in `/help` now, lets just delete them?

**Comment by cammace** [comment]
You've stretched two images, how about just making new screenshots for these?

**Comment by langsmith** [comment]
Yes, I know they're stretched. Batfish and this pr are wonky. I commit a new image but don't see it reflected in the test site that I run locally. Work in progress...

**Comment by langsmith** [comment]
Images have been fixed @cammace 

ezgif com-resize 3

**Pull request merged**
