### PR TITLE
Adding dedicated gestures page

### PR DESCRIPTION
**Pull request by langsmith**
Resolves https://github.com/mapbox/android-docs/issues/306 by adding docs section for https://github.com/mapbox/mapbox-gestures-android to the https://www.mapbox.com/android-docs/map-sdk/overview/ left hand sidebar

### CODE REVIEW

**Comment by langsmith** [comment]
cc @LukasPaczos  for eventual 📜🖊 

Things are set up for additions to this branch's `gestures.md` file 😉 


screen shot 2018-02-27 at 2 59 12 pm

**Comment by LukasPaczos** [comment]
Awesome, thank you very much @langsmith. I'll pick this up when the first stable release of the gestures library is available.

**Comment by LukasPaczos** [comment]
Added a brief gestures documentation.
Please review @langsmith and let me know what you think.
screenshot from 2018-04-05 15-46-29

**Comment by LukasPaczos** [comment]
I think we should wait with merging this one until `6.0.0` is released, right?

**Comment by langsmith** [comment]
Sure, let's wait

**Comment by LukasPaczos** [comment]
Ready to merge @langsmith!

**Pull request merged**
