### PR TITLE
Adds analytics

### PR DESCRIPTION
**Pull request by ericrwolfe**
We currently don't track any analytics for https://www.mapbox.com/android-docs 😱.

This adds analytics tracking.

cc @langsmith @cammace

### CODE REVIEW

**Comment by langsmith** [comment]
Thanks @ericrwolfe

**Comment by ericrwolfe** [comment]
@davidtheclark do you have any opinions on how this should be done? @mick said you were thinking about consistency across our internal sites.

**Comment by davidtheclark** [comment]
@ericrwolfe: This is being incorporated into #157. 

That way this should be done in the future is to use https://github.com/mapbox/dotcom-page-shell. Currently all Jekyll sites and www use it. I think the only reason Android docs were missing out was because they missed out on the common shell stuff when switching to Gatsby.

**Comment by ericrwolfe** [comment]
@davidtheclark cool! That's quite a PR, when are you planning to land it?

Should I close this?

**Comment by davidtheclark** [comment]
@ericrwolfe: Should land within a day or two. So yeah, I guess we should close this. This is a good reminder to double-check that the analytics work in the Batfish branch.

**Pull request closed without merging**
