### PR TITLE
Bump example code for Maps v7.0.0 (and refreshes Nav examples)

### PR DESCRIPTION
**Pull request by colleenmcginnis**
This PR pulls in the most recent example code from both the Maps SDK and Navigation SDK demo apps. It also removes example pages that use activities that were removed and updates example pages that use activities that were modified. Here's a summary of the user-facing changes:

- [deleted] [Draw a custom marker icon](https://docs.mapbox.com/android/maps/examples/draw-a-custom-marker-icon/) from `DrawCustomMarkerActivity.java`
- [deleted] [Draw a marker](https://docs.mapbox.com/android/maps/examples/draw-a-marker/) from `DrawMarkerActivity.java`

I also wrote a script to check which activities from the maps demo app do not currently have an example page in this repo: 

- KotlinSimpleMapViewActivity.kt
- BathymetryActivity.java
- CircleLayerClusteringActivity.java
- KotlinStyleCirclesCategoricallyActivity.kt
- LineGradientActivity.java
- SatelliteLandSelectActivity.java
- GeocodingActivity.java
- IsochroneActivity.java
- TilequeryActivity.java
- AnimatedImageGifActivity.java
- CalendarIntegrationActivity.java
- DashedLineDirectionsPickerActivity.java
- LocationPickerActivity.java
- MagicWindowKotlinActivity.kt
- MapFogBackgroundActivity.java
- MarkerFollowingRouteActivity.java
- SnakingDirectionsRouteActivity.java
- SpaceStationLocationActivity.java
- KotlinLocationComponentActivity.kt
- LocationComponentOptionsActivity.java
- MarkerViewPluginActivity.java
- ClickToAddImageActivity.java

@langsmith do we want to add these as examples in a follow-up PR? If it would be easier we can move this discussion to a separate ticket.

### CODE REVIEW

**Comment by langsmith** [comment]
>do we want to add these as examples in a follow-up PR?

Yea, I will make a ticket and subsequent pr to add the missing examples.

**Comment by langsmith** [comment]
https://github.com/mapbox/android-docs/issues/831

**Comment by langsmith** [comment]
`Add a marker` needs to be fixed on https://www.mapbox.com/install/android/complete  😢 'cause that demo example no longer exists.

**Comment by langsmith** [comment]
Same with `Add a GeoJSON line` 😱

**Comment by riastrad** [comment]
Confirmed what @langsmith saw on `www.mapbox.com/install/android/complete`. Cut a separate ticket to keep track.

💁‍♂️ https://github.com/mapbox/www.mapbox.com/issues/3856

**Comment by colleenmcginnis** [comment]
Oh no! I was going to ask if we should put a new example for `MarkerViewPluginActivity.java` at the old marker example URL to prevent broken links and encourage users to use the new recommended method. I mean we still _can_ if it makes sense!  💁

**Comment by riastrad** [comment]
I'm always in favor of preventing broken links, @colleenmcginnis! But since we were in a hurry to get 7.0.0 examples up on the page, maybe it would be best to open up a separate ticket for that effort?

**Pull request merged**
